// dsh-kanban 看板插件的 skill 内容：运行时注册进宿主 skills 注册表（全局层，所有会话可见）。
// 内容面向模型，zh/en 双语：宿主按当前语言挑选（跟随平台设置 locale.preference，设置页 Language 行切换）。
export const KANBAN_SKILLS = {
  zh: {
    name: 'kanban',
    description: 'DSH 看板工作台：把多步骤/长期/定时/需委派的工作拆成任务卡片，委派给子代理执行并跟踪进度；人通过界面「看板」标签页看同一块板。',
    whenToUse: '当任务多步骤、耗时长、需要定时或重复执行、适合拆解后委派给子代理，或用户提到看板/任务时使用。一步能完成的小事不要建卡，直接做。',
    content: [
      '## 用途',
      '',
      'kanban 是主 Agent 的工作规划与委派通道。你把工作拆成任务卡片放进看板（`kanban_create_task`），**待办/就绪列的任务会自动派发**给 DSH 子代理执行（`kanban_dispatch_task` 仅用于手动提前派发或重试），并用读工具（`kanban_list_boards` / `kanban_list_tasks` / `kanban_get_task`）跟踪状态与进度。',
      '',
      '人通过界面上的「看板」标签页实时看到同一块板：卡片的标题、正文、评论、执行进度与结果摘要。**给人看的信息请写进卡片正文或评论，而不是只在对话里说。**',
      '',
      '## 何时使用 / 何时不用',
      '',
      '- 使用：多步骤任务拆解；长时间运行的任务；定时或重复任务（schedule）；适合委派给子代理独立完成的任务；用户明确要求记录到看板。',
      '- 不使用：一步完成的小操作直接做，不要建卡；也不要把看板当聊天记录使用。',
      '',
      '## 卡片生命周期',
      '',
      '`triage`(待细化) → `todo`(待办) → `scheduled`(定时) → `ready`(就绪) → `running`(运行中，只能经派发进入) → `done`(完成) / `blocked`(阻塞) → `review`(审核) / `archived`(归档)。',
      '',
      '- `todo`/`ready` 列的任务由事件循环自动派发（10s 内触发），派发成功后自动进入 `running`；只想记录不执行的卡放 `triage`。',
      '- 设了父卡片（schedule.parentId）的卡在父卡片完成/归档前不会被自动派发（任何列生效）。',
      '- 子代理完成后自动转 `done` 并回写结果摘要；失败或心跳丢失转 `blocked`（错误原因在卡片事件里）。',
      '- `running` 任务不能直接改状态：先 `kanban_stop_task` 停回 `triage`（停回待办/就绪会被自动重新派发），再移动。',
      '',
      '## 工具速览',
      '',
      '- `kanban_list_boards`：看有哪些看板及各自负载。',
      '- `kanban_list_tasks`：按看板/状态/优先级/关键词查任务（先看板，再动手）。',
      '- `kanban_get_task`：查单个任务的完整信息，含评论、事件、最近一次运行的进度与结果。',
      '- `kanban_create_task`：建卡（title 必填；body/status/priority/assignee/schedule 可选）。',
      '- `kanban_update_task`：改标题/正文/状态/优先级/负责人/定时。',
      '- `kanban_add_comment`：给任务追加评论（面向人）。',
      '- `kanban_dispatch_task`：手动立即派发待办/就绪任务（默认已自动派发，一般无需手动）；可选 `instructions` 补充本轮要求。',
      '- `kanban_stop_task`：终止运行中的任务，移回 `triage`（待细化）。',
      '- `kanban_delete_task`：删除任务（不可恢复）。',
      '- `kanban_create_board`：新建看板。',
      '',
      '## 标准工作流',
      '',
      '1. 收到多步骤/长期任务时，先 `kanban_list_boards` 选看板（没有就 `kanban_create_board` 建一个），再按验收目标拆卡（`kanban_create_task`）。',
      '2. 卡片标题用动词开头、一句话说清目标（如「重构 xx 模块的错误处理」）；正文写清验收标准与背景；需要执行的卡建成 `todo`/`ready`（会自动派发），只想记录不执行的卡放 `triage`。',
      '3. 自动派发 10s 内触发（也可用 `kanban_dispatch_task` 手动提前派发；子代理模型用 assignee 指定，留空跟随会话默认）。',
      '4. 派发是异步的：用 `kanban_get_task` 轮询 `run` 的 `progress`（最近 50 行）与 `outcome`（done/error/terminated）；不要在派发后干等。',
      '5. 结果出来后：读摘要，确认验收；给用户一句话结论；如有遗留事项用 `kanban_add_comment` 记到卡片上。',
      '',
      '## 字段约定',
      '',
      '- `priority`：0-9，越大越优先（0 默认；7-9 高 / 4-6 中 / 1-3 低）。',
      '- `assignee`：子代理模型名；留空表示跟随当前会话的默认模型。',
      '- `schedule`：`interval` 每 N 分钟重复、`daily` 每天固定时刻（HH:MM）只对 `scheduled` 列生效；`parentId` 是全局门禁——设了父卡片的卡在父卡片完成/归档前不会被自动派发（任何列）。重复任务完成后自动回排 `scheduled`。',
      '',
      '## 与子代理协作',
      '',
      '- 派发后子代理会按任务正文执行，并把进度追加到工作区 `DSH-kanban/runs/<任务ID>.progress`，看板实时回显。',
      '- 子代理可用 `kanban_add_comment` 追加评论，但被要求不要修改任务状态（状态由看板结算逻辑管理）。',
      '- 子代理 30 分钟无活动会被判定心跳丢失、终止并转 `blocked`；长步骤任务请在正文里说明。',
      '',
      '## 注意事项',
      '',
      '- 建卡/改卡后把任务 id 与看板告诉用户，便于对照界面。',
      '- 所有工具省略 `board` 时用第一个看板；`kanban_get_task`/`kanban_update_task`/`kanban_add_comment`/`kanban_stop_task`/`kanban_delete_task` 省略 `board` 时会在全部看板中查找任务 id。',
      '- 把卡放进待办/就绪列就会派发子代理执行（消耗 token）：只记录不动手的卡放「待细化」或「定时（纯停放）」。',
      '- 保持卡片整洁：已完成的事记在事件与摘要里，不要在标题里堆状态。',
    ].join('\n'),
  },
  en: {
    name: 'kanban',
    description: 'DSH kanban workbench: break multi-step, long-running, scheduled, or delegatable work into task cards, dispatch them to subagents, and track progress; people watch the same board from the Kanban tab in the UI.',
    whenToUse: 'Use when a task has multiple steps, runs long, needs scheduling or repetition, suits delegation to a subagent, or when the user mentions kanban/tasks. Do not create cards for small one-step actions — just do them.',
    content: [
      '## Purpose',
      '',
      'kanban is the main Agent\'s planning and delegation channel. You break work into task cards on the board (`kanban_create_task`); **tasks in the todo/ready columns auto-dispatch** to DSH subagents (`kanban_dispatch_task` is only for dispatching early or retrying manually), and you track status and progress with the read tools (`kanban_list_boards` / `kanban_list_tasks` / `kanban_get_task`).',
      '',
      'People see the same board live in the UI\'s Kanban tab: card titles, bodies, comments, execution progress, and result summaries. **Write information meant for humans into card bodies or comments, not only in the chat.**',
      '',
      '## When to use / when not to use',
      '',
      '- Use: breaking multi-step tasks down; long-running tasks; scheduled or repeating tasks (schedule); tasks that suit delegation to a subagent; the user explicitly asks to record to the board.',
      '- Do not use: do small one-step actions directly without creating a card; do not use the board as a chat log.',
      '',
      '## Card lifecycle',
      '',
      '`triage`(to refine) → `todo`(to do) → `scheduled`(scheduled) → `ready`(ready) → `running`(running, entered only via dispatch) → `done`(done) / `blocked`(blocked) → `review`(review) / `archived`(archived).',
      '',
      '- Tasks in the `todo`/`ready` columns are auto-dispatched by the event loop (within ~10s) and then enter `running`; put record-only cards in `triage`.',
      '- A card with a parent card (schedule.parentId) is not auto-dispatched until the parent completes or is archived (any column).',
      '- When a subagent finishes, the task turns `done` automatically and the result summary is written back; failure or heartbeat loss turns it `blocked` (the error reason is in the card\'s events).',
      '- A `running` task cannot change status directly: first `kanban_stop_task` back to `triage` (back to todo/ready would auto re-dispatch), then move it.',
      '',
      '## Tool overview',
      '',
      '- `kanban_list_boards`: see which boards exist and their load.',
      '- `kanban_list_tasks`: query tasks by board/status/priority/keyword (look at boards first, then act).',
      '- `kanban_get_task`: read one task\'s full details — comments, events, and the latest run\'s progress and result.',
      '- `kanban_create_task`: create a card (title required; body/status/priority/assignee/schedule optional).',
      '- `kanban_update_task`: edit title/body/status/priority/assignee/schedule.',
      '- `kanban_add_comment`: append a comment to a task (meant for humans).',
      '- `kanban_dispatch_task`: manually dispatch a todo/ready task right away (auto-dispatch already covers them, so this is rarely needed); optional `instructions` add requirements for this round.',
      '- `kanban_stop_task`: terminate a running task, back to `triage` (to refine).',
      '- `kanban_delete_task`: delete a task (irrecoverable).',
      '- `kanban_create_board`: create a board.',
      '',
      '## Standard workflow',
      '',
      '1. For a multi-step/long-running task, first `kanban_list_boards` to pick a board (or `kanban_create_board` if none exists), then split the work into cards by acceptance goals (`kanban_create_task`).',
      '2. Start card titles with a verb and state the goal in one sentence (e.g. "Refactor error handling in module xx"); write acceptance criteria and background in the body; make cards meant for execution `todo`/`ready` (they auto-dispatch), and record-only cards `triage`.',
      '3. Auto-dispatch fires within ~10s (or use `kanban_dispatch_task` to dispatch early; the subagent model is set via assignee, leave empty to follow the session default).',
      '4. Dispatch is asynchronous: poll `run.progress` (last 50 lines) and `outcome` (done/error/terminated) with `kanban_get_task`; do not just wait after dispatching.',
      '5. When the result arrives: read the summary, confirm acceptance; give the user a one-line conclusion; record any follow-ups on the card with `kanban_add_comment`.',
      '',
      '## Field conventions',
      '',
      '- `priority`: 0-9, higher first (0 default; 7-9 high / 4-6 medium / 1-3 low).',
      '- `assignee`: subagent model name; leave empty to follow the current session\'s default model.',
      '- `schedule`: `interval` repeats every N minutes and `daily` fires at a fixed time each day (HH:MM) — these take effect only in the `scheduled` column; `parentId` is a global gate — a card with a parent card is not auto-dispatched until the parent completes or is archived (any column). Repeating tasks automatically return to `scheduled` after completing a round.',
      '',
      '## Working with subagents',
      '',
      '- After dispatch, the subagent works from the task body and appends progress lines to the workspace file `DSH-kanban/runs/<taskId>.progress`; the board shows them live.',
      '- The subagent may append comments via `kanban_add_comment`, but is asked not to modify task status (status is managed by the board\'s settlement logic).',
      '- A subagent idle for 30 minutes is judged as heartbeat-lost, terminated, and turned `blocked`; mention long-running steps in the task body.',
      '',
      '## Notes',
      '',
      '- After creating/editing a card, tell the user the task id and board so they can match them in the UI.',
      '- All tools use the first board when `board` is omitted; `kanban_get_task`/`kanban_update_task`/`kanban_add_comment`/`kanban_stop_task`/`kanban_delete_task` search every board for the task id when `board` is omitted.',
      '- Putting a card into todo/ready dispatches a subagent (spends tokens): keep record-only cards in triage or parked in scheduled.',
      '- Keep cards tidy: record finished work in events and summaries, not by stacking statuses into titles.',
    ].join('\n'),
  },
}
